version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /Legacy.Maliev.AuthService.Api
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /Legacy.Maliev.AuthService.IdentityMigration
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
