using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Xml.Linq;
using Legacy.Maliev.AuthService.Infrastructure;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;

namespace Legacy.Maliev.AuthService.Tests;

// Synthetic protected ring only. Production key/certificate material is never loaded by these tests.
internal sealed class EmployeeRememberedKeyRingFixture : IAsyncDisposable
{
    internal const string Discriminator = "/original-synthetic-app/";
    private const string CertificatePassword = "fixture-only-custody-password";
    private readonly string directory = Path.Combine(Path.GetTempPath(), "auth-remembered-" + Guid.NewGuid().ToString("N"));
    private readonly X509Certificate2 certificate;
    private readonly ServiceProvider writer;
    private readonly string connection;
    private EmployeeRememberedKeyRingFixture(string connection)
    {
        this.connection = new NpgsqlConnectionStringBuilder(connection) { Pooling = false }.ConnectionString;
        Directory.CreateDirectory(directory);
        try
        {
            using var rsa = RSA.Create(2048);
            var request = new CertificateRequest("CN=Synthetic employee key custody", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
            using var generated = request.CreateSelfSigned(DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddDays(2));
            var path = Path.Combine(directory, "synthetic-custody.pfx");
            File.WriteAllBytes(path, generated.Export(X509ContentType.Pfx, CertificatePassword));
            certificate = X509CertificateLoader.LoadPkcs12FromFile(path, CertificatePassword, X509KeyStorageFlags.EphemeralKeySet);
            try { writer = CreateWriter(Discriminator); }
            catch { certificate.Dispose(); throw; }
        }
        catch { Directory.Delete(directory, recursive: true); throw; }
    }

    public IReadOnlyDictionary<string, string?> Settings => new Dictionary<string, string?>
    {
        ["ConnectionStrings:employee-data-protection"] = connection,
        ["EmployeeRememberedClient:OriginalApplicationDiscriminator"] = Discriminator,
        ["EmployeeRememberedClient:CertificatePath"] = Path.Combine(directory, "synthetic-custody.pfx"),
        ["EmployeeRememberedClient:CertificatePassword"] = CertificatePassword,
    };

    public static async Task<EmployeeRememberedKeyRingFixture> CreateAsync(PostgresFixture postgres, bool seedKey = true)
    {
        var fixture = new EmployeeRememberedKeyRingFixture(await postgres.CreateDatabaseAsync());
        try
        {
            await using var db = new NpgsqlConnection(fixture.connection);
            await db.OpenAsync();
            await using var command = db.CreateCommand();
            command.CommandText = """
                CREATE TABLE "DataProtectionKeys" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FriendlyName" text NULL, "Xml" text NULL);
                """;
            await command.ExecuteNonQueryAsync();
            if (seedKey) fixture.writer.GetRequiredService<IKeyManager>().CreateNewKey(DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddDays(90));
            return fixture;
        }
        catch { await fixture.DisposeAsync(); throw; }
    }

    public string Ticket(string userId, string stamp, string variant, DateTimeOffset now)
    {
        var issued = variant == "young" ? now.AddDays(-2) : now.AddDays(-8);
        var expires = variant == "expired" ? now.AddMinutes(-1) : issued.AddDays(14);
        var claims = new[] { new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.Name, userId),
            new System.Security.Claims.Claim(new IdentityOptions().ClaimsIdentity.SecurityStampClaimType, stamp) };
        var principal = new System.Security.Claims.ClaimsPrincipal(new System.Security.Claims.ClaimsIdentity(claims, IdentityConstants.TwoFactorRememberMeScheme));
        var ticket = new AuthenticationTicket(principal, new AuthenticationProperties { IsPersistent = true, AllowRefresh = variant == "no-renewal-flag" ? false : null, IssuedUtc = issued, ExpiresUtc = expires }, IdentityConstants.TwoFactorRememberMeScheme);
        if (variant == "wrong-discriminator")
        {
            using var wrong = CreateWriter("/different-synthetic-app/");
            return Format(wrong.GetRequiredService<IDataProtectionProvider>(), IdentityConstants.TwoFactorRememberMeScheme).Protect(ticket);
        }
        var purpose = variant == "wrong-purpose" ? "different-cookie-scheme" : IdentityConstants.TwoFactorRememberMeScheme;
        return Format(writer.GetRequiredService<IDataProtectionProvider>(), purpose).Protect(ticket);
    }

    public AuthenticationTicket? ReadTicket(string value) => Format(writer.GetRequiredService<IDataProtectionProvider>(), IdentityConstants.TwoFactorRememberMeScheme).Unprotect(value);
    public IReadOnlyCollection<XElement> ReadProtectedElements() => new EmployeeDataProtectionXmlRepository(connection).GetAllElements();

    private ServiceProvider CreateWriter(string application)
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddDataProtection().SetApplicationName(application).ProtectKeysWithCertificate(certificate).DisableAutomaticKeyGeneration();
        services.Configure<KeyManagementOptions>(options => options.XmlRepository = new EmployeeDataProtectionXmlRepository(connection));
        return services.BuildServiceProvider();
    }
    private static TicketDataFormat Format(IDataProtectionProvider provider, string scheme) =>
        new(provider.CreateProtector("Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware", scheme, "v2"));

    public async ValueTask DisposeAsync()
    {
        try { await writer.DisposeAsync(); }
        finally
        {
            certificate.Dispose();
            Directory.Delete(directory, recursive: true);
            if (Directory.Exists(directory)) throw new IOException("Synthetic custody fixture directory remained after cleanup.");
        }
    }
}
