<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <RuntimeHostConfigurationOption Include="Microsoft.AspNetCore.Identity.CheckPasswordSignInAlwaysResetLockoutOnSuccess" Value="true" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <ProjectReference Include="../../Legacy.Maliev.AuthService.Tests/Legacy.Maliev.AuthService.Tests.csproj" />
  </ItemGroup>
</Project>
