-- Source-only schema for the separate employee-owned PostgreSQL key store.
-- Not executed by application startup. Original key IDs/activation/expiration/revocations
-- must survive protected custody adoption; no empty-ring or replacement-key fallback.
CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FriendlyName" text NULL,
    "Xml" text NULL
);
-- Owner/grants and protected original-key adoption require their own reviewed receipt.
