using Microsoft.EntityFrameworkCore.Migrations;

namespace Legacy.Maliev.AuthService.Infrastructure.Migrations;

internal static class LegacyIdentityAncillarySchema
{
    internal static void ValidateEmployeeTokenStore(MigrationBuilder builder) => builder.Sql("""
        DO $body$
        DECLARE token_table regclass := to_regclass('"AspNetUserTokens"');
        DECLARE shape text[];
        DECLARE key_columns text[];
        BEGIN
            IF token_table IS NULL THEN
                RAISE EXCEPTION 'Reviewed employee Identity token-store migration is required';
            END IF;
            SELECT array_agg(attname || ':' || format_type(atttypid, atttypmod) || ':' || attnotnull::text ORDER BY attname)
              INTO shape FROM pg_attribute WHERE attrelid = token_table AND attnum > 0 AND NOT attisdropped;
            IF shape IS DISTINCT FROM ARRAY[
                'LoginProvider:text:true', 'Name:text:true',
                'UserId:character varying(450):true', 'Value:text:false']::text[] THEN
                RAISE EXCEPTION 'Employee Identity token-store columns do not match the reviewed model';
            END IF;
            SELECT array_agg(attribute.attname::text ORDER BY key.ordinality) INTO key_columns
              FROM pg_constraint constraint_row
              CROSS JOIN LATERAL unnest(constraint_row.conkey) WITH ORDINALITY AS key(attnum, ordinality)
              JOIN pg_attribute attribute ON attribute.attrelid = token_table AND attribute.attnum = key.attnum
              WHERE constraint_row.conrelid = token_table AND constraint_row.contype = 'p';
            IF key_columns IS DISTINCT FROM ARRAY['UserId', 'LoginProvider', 'Name']::text[] THEN
                RAISE EXCEPTION 'Employee Identity token-store primary key does not match the reviewed model';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint constraint_row
                JOIN pg_attribute child ON child.attrelid = token_table AND child.attname = 'UserId'
                JOIN pg_attribute parent ON parent.attrelid = '"AspNetUsers"'::regclass AND parent.attname = 'Id'
                WHERE constraint_row.conrelid = token_table AND constraint_row.contype = 'f'
                  AND constraint_row.confrelid = '"AspNetUsers"'::regclass
                  AND constraint_row.conkey = ARRAY[child.attnum]::smallint[]
                  AND constraint_row.confkey = ARRAY[parent.attnum]::smallint[]
                  AND constraint_row.confdeltype = 'c'
                  AND constraint_row.convalidated
            ) THEN
                RAISE EXCEPTION 'Employee Identity token-store ownership cascade does not match the reviewed model';
            END IF;
        END
        $body$;
        """);

    internal static void Create(MigrationBuilder builder, bool includeTokens)
    {
        builder.Sql("""
            CREATE TABLE "AspNetRoles" (
                "Id" character varying(450) NOT NULL,
                "Name" character varying(256) NULL,
                "NormalizedName" character varying(256) NULL,
                "ConcurrencyStamp" text NULL,
                CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
            );
            CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
            CREATE TABLE "AspNetRoleClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "RoleId" character varying(450) NOT NULL,
                "ClaimType" text NULL,
                "ClaimValue" text NULL,
                CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
            CREATE TABLE "AspNetUserClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" character varying(450) NOT NULL,
                "ClaimType" text NULL,
                "ClaimValue" text NULL,
                CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
            CREATE TABLE "AspNetUserLogins" (
                "LoginProvider" text NOT NULL,
                "ProviderKey" text NOT NULL,
                "ProviderDisplayName" text NULL,
                "UserId" character varying(450) NOT NULL,
                CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
            CREATE TABLE "AspNetUserRoles" (
                "UserId" character varying(450) NOT NULL,
                "RoleId" character varying(450) NOT NULL,
                CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
            """);
        if (includeTokens)
        {
            builder.Sql("""
                CREATE TABLE "AspNetUserTokens" (
                    "UserId" character varying(450) NOT NULL,
                    "LoginProvider" text NOT NULL,
                    "Name" text NOT NULL,
                    "Value" text NULL,
                    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );
                """);
        }
    }
}
